mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^newsfeed/', include('newsfeed.urls')),
	url(r'^polls/', include('polls.urls')),
	url(r'^savingscalculator/', include('savingscalculator.urls')),
    url(r'^admin/', admin.site.urls),
]

savingscalculator/urls.py
from django.conf.urls import url

from . import views

app_name = 'savingscalculator'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^queries$', views.queries, name='queries'),
]

savingscalculator/models.py
from django.db import models

# Create your models here.

class Calculator(models.Model):
	initial_capital = models.CharField(max_length=50)
	number_of_years = models.CharField(max_length=50)
	interest_rate = models.CharField(max_length=50)
	final_capital = models.CharField(max_length=50)

savingscalculator/views.py
from django.shortcuts import render

from .models import Calculator

def index(request):

	context = {}

	if(request.method == "POST"):

		try:

			initialcapital = float(request.POST.get('initial'))
			years = float(request.POST.get('years'))
			rate = float(request.POST.get('interest'))
			finalcapital = initialcapital * (1 + ((rate/100)/12))**(12*years)

			if(initialcapital<=0):
				context['error'] = "Please enter a positive number in the 'Initial Capital' field."
			elif (years<=0):
				context['error'] = "Please enter a positive number in the 'Number of Years' field."
			elif (rate<=0):
				context['error'] = "Please enter a positive number in the 'Interest Rate' field."

			else:
				context['initial'] = initialcapital
				context['years'] = years
				context['interest'] = rate
				context['final'] = finalcapital

				c = Calculator(initial_capital = initialcapital, number_of_years = years, interest_rate = rate, final_capital = finalcapital)
				c.save()

		except ValueError:
			context['error'] = "Error! Please enter a value in each field."

	return render(request, "savingscalculator/index.html", context)

def queries(request):

	Queries = Calculator.objects.all()

	context = {'Queries' : Queries}
	
	return render(request, "savingscalculator/queries.html", context)

savingscalculator/templates/savingscalculator/index.html
<!DOCTYPE html>

<!-- HTML taken from http://savings-oliva.apps.devcloud.eecs.qmul.ac.uk/ -->
<head>
   <title>My Cool Savings Calculator</title>
   <style>
   h1 {
      padding-bottom: 0em;
      margin-bottom: 0em;
   }
   table {
      padding-top: 0em;
      margin-top: 0em;
   }
   </style>
</head>
<body>
   <h1>Savings Calculator</h1>
   <b style="color:#FF0000";>{{error}}</b>
   <table>
   <form method='POST'>
   {% csrf_token %}
   <tr>
      <td><label>Initial Capital:</label>
      {% if final > 0 %}
      <td><input type='text' name='initial' value={{initial}}></input></td>
      {% else %}
      <td><input type='text' name='initial'></input></td>
      {% endif %}
   </tr>
   <br>
   <tr>
      <td><label>Number of Years:</label>
      {% if final > 0 %}
      <td><input type='text' name='years' value={{years}}></input></td>
      {% else %}
      <td><input type='text' name='years' value='5'></input></td>
      {% endif %}      
   </tr>
   <br>
   <tr>
      <td><label>Interest rate (annual):</label>
      {% if final > 0 %}
      <td><input type='text' name='interest' value={{interest}}></input></td>
      {% else %}
      <td><input type='text' name='interest' value='3.5'></input></td>
      {% endif %}
   </tr>
   <br>
   <tr>
      <td></td>
      <td><input type='submit'></input></td>
   </tr>
   </form>
   </table>
   <h2>Capital at the end of {{years}} years: {{final|floatformat:2}}</h2>
<h3>Check previous queries <a href="{% url 'savingscalculator:queries' %}">here</a></h3>
</body>

savingscalculator/templates/savingscalculator/queries.html
<!DOCTYPE html>
<head>
   <title>My Cool Savings Calculator: List of Queries</title>
   <style>
   td {
      text-align: center;
   }
   </style>
</head>
<body>
<h1>History of Queries</h1>
<table>
<tr>
   <th>Initial Capital</th>
   <th>Years</th>
   <th>Rate</th>
   <th>Final Capital</th>
</tr>
<br>
{% for query in Queries %}
<tr>
   <td>{{query.initial_capital}}</td>
   <td>{{query.number_of_years}}</td>
   <td>{{query.interest_rate}}</td>
   <td>{{query.final_capital}}</td>
</tr>
{% endfor %}
</table>
<br>
<h3><a href="{% url 'savingscalculator:index' %}">Make new query</a></h3>
</body>